/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 独占导入的附件位置和提交后警告。 */
export interface JsImportedAttachment {
  /** 实际库内路径，同名避让后可能与原文件名不同。 */
  path: string
  /** 文件已落盘后发生的索引或同步错误。 */
  warning?: string
}
/** 导入用户选择的附件字节，返回实际位置；路径、大小与写盘错误由内核传播。 */
export declare function attachmentImport(from: string, name: string, bytes: Buffer): JsImportedAttachment
/** 一条书签；`kind` 为 `file`/`folder`（`path`）、`heading`（`path` 与 `heading`）或 `search`（`query`）。 */
export interface JsBookmark {
  /** 书签种类。 */
  kind: string
  /** 库内相对路径；文件、文件夹与标题书签必填。 */
  path?: string
  /** 标题原文；只用于标题书签。 */
  heading?: string
  /** 查询文本；只用于搜索书签。 */
  query?: string
  /** 自定义显示名。 */
  title?: string
}
/**
 * 读出库内书签；文件不存在时为空。
 *
 * # Errors
 *
 * 未打开库、读盘失败或书签文件损坏。
 */
export declare function bookmarksList(): Array<JsBookmark>
/**
 * 整体替换书签清单；损坏的旧文件先备份再覆盖。
 *
 * # Errors
 *
 * 未打开库、书签字段无效或写盘失败。
 */
export declare function bookmarksSet(items: Array<JsBookmark>): void
/**
 * 列出库内相对路径。
 *
 * # Errors
 *
 * 未打开库或读目录失败。
 */
export declare function vaultList(): Array<string>
/** 文件树条目，包含空文件夹。 */
export interface JsVaultEntry {
  /** 库内相对路径。 */
  path: string
  /** file 或 directory。 */
  kind: string
  /** 仅在草稿无法对应真实文件条目时设置。 */
  recoveryOnly?: boolean
}
/** 列出完整目录；未打开库或目录读取失败时返回错误。 */
export declare function vaultEntries(): Array<JsVaultEntry>
/**
 * 创建笔记或文件夹；`content` 是文件初始字节（缺省为空），创建与写入
 * 是同一次独占提交。非法类型、同名目标、目录携带内容或磁盘失败时拒绝。
 */
export declare function entryCreate(path: string, kind: string, content?: Buffer | undefined | null): JsRenameOutcome
/** 移入系统废纸篓；失败不退化为永久删除，未保存草稿阻止操作。 */
export declare function entryTrash(path: string): JsRenameOutcome
/** 批量预检的独立条目，不包含未经确认的覆盖或永久删除选项。 */
export interface JsEntryMutation {
  /** 规范的库内源路径。 */
  from: string
  /** 缺席表示废纸篓操作，否则为规范移动目标。 */
  to?: string
}
/** 预检整批操作；不修改用户文件，路径、草稿或目标冲突通过异常返回。 */
export declare function entryCheckBatch(changes: Array<JsEntryMutation>): void
/** 获取经过库根校验的现有路径，只供主进程调用系统文件管理器。 */
export declare function entryPath(path: string): string
/** 文件已经完成改名，索引或日志清理可能仍需重试。 */
export interface JsRenameOutcome {
  /** 提交后的警告；无警告时缺失。 */
  warning?: string
}
/**
 * 将 `from` 改名为 `to` 并更新全库链接，返回提交后的警告。
 *
 * # Errors
 *
 * 未打开库、目标已存在或写盘失败。
 */
export declare function entryRename(from: string, to: string): JsRenameOutcome
/** 首个失败的源路径与原因；空路径表示进度回调失败。 */
export interface JsRenameBatchIssue {
  /** 规范的库内源路径，或表示批次错误的空字符串。 */
  path: string
  /** 可直接展示的失败原因。 */
  message: string
}
/** 已提交前缀是重试的唯一边界，索引警告不会让已完成文件再次执行。 */
export interface JsRenameBatchOutcome {
  /** 已独立持久化的条目数。 */
  completed: number
  /** 首个执行或回调失败，主动停止时缺省。 */
  issue?: JsRenameBatchIssue
  /** 提交后的清理、书签或索引警告。 */
  warning?: string
}
/**
 * 整批预检后复用快照逐项移动；同步回调收到完成数，返回 false 在事务之间停止。
 * 回调只能保存外部会话或读取停止信号，不能重入内核；异常进入结果并收尾索引。
 * # Errors
 * 未打开库、预检或快照失败时抛错且本批尚未提交；执行后的错误保留真实完成数。
 */
export declare function entryRenameBatch(changes: Array<JsEntryMutation>, progress: (completed: number) => boolean): JsRenameBatchOutcome
/**
 * 读取文件原始字节。
 *
 * # Errors
 *
 * 未打开库、越界或不存在。
 */
export declare function fileRead(rel: string): Buffer
/** 已持久化的恢复草稿。 */
export interface JsDraft {
  /** 普通草稿为最新内容；存在 editor 时为重建源码映射的原始字节。 */
  bytes: Buffer
  /** 原编辑基准；缺失表示新文件。 */
  base?: Buffer
  /** 版本化的编辑器恢复内容；没有时按普通 Markdown 字节恢复。 */
  editor?: string
}
/** 编辑器加载快照，文件删除时仍可恢复草稿。 */
export interface JsFileSnapshot {
  /** 磁盘内容；缺失时通过 disk_error 区分删除与读取失败。 */
  disk?: Buffer
  /** 原路径不可读时保留草稿，并携带原因。 */
  diskError?: string
  /** 尚未提交的编辑。 */
  draft?: JsDraft
}
/**
 * 获取 `rel` 的磁盘内容与恢复草稿。
 *
 * # Errors
 *
 * 未打开库、越界或读取失败。
 */
export declare function fileSnapshot(rel: string): JsFileSnapshot
/**
 * 持久化带版本的编辑恢复数据，保持原笔记字节不变。
 *
 * # Errors
 * 未打开库、路径或数据非法、恢复记录冲突或数据库不可写。
 */
export declare function filePreserveDraft(rel: string, source: Buffer, expected: Buffer | undefined | null, editor: string): void
/** 文件提交结果，冲突时附带磁盘版本。 */
export interface JsWriteResult {
  /** `saved` 或 `conflict`。 */
  status: string
  /** 冲突的磁盘字节；缺失也可能表示文件被删除。 */
  disk?: Buffer
  /** 已提交后的同步、索引或清理警告。 */
  warning?: string
}
/**
 * 按 `expected` 基准保存 `bytes`，返回提交状态或冲突。
 *
 * # Errors
 *
 * 未打开库、越界、草稿持久化或内容提交失败。
 */
export declare function fileWrite(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): JsWriteResult
/** 新副本的路径与提交后警告。 */
export interface JsSavedCopy {
  /** 实际创建的相对路径。 */
  path: string
  /** 内容已保存后的警告。 */
  warning?: string
}
/**
 * 将当前 `bytes` 写入唯一命名的新副本，`expected` 用于恢复基准。
 *
 * # Errors
 *
 * 未打开库、路径非法或副本提交失败。
 */
export declare function fileWriteCopy(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): JsSavedCopy
/** 图谱节点：笔记或死链目标。 */
export interface JsGraphNode {
  /** 笔记的库内相对路径；死链为去掉锚点后的目标原文。 */
  path: string
  /** 展示标题。 */
  title: string
  /** 标签，升序。 */
  tags: Array<string>
  /** 是否为尚未创建的死链目标。 */
  dead: boolean
}
/** 图谱中的有向边。 */
export interface JsGraphEdge {
  /** 源笔记路径。 */
  from: string
  /** 目标节点的 `path`。 */
  to: string
  /** 这对起止之间的链接条数。 */
  count: number
}
/** 全库图谱。 */
export interface JsGraph {
  /** 节点，按路径升序。 */
  nodes: Array<JsGraphNode>
  /** 边，按起止升序。 */
  edges: Array<JsGraphEdge>
}
/**
 * 全库关系图谱；`include_dead` 为真时死链目标作为虚节点出现。
 *
 * # Errors
 *
 * 未打开库或索引查询失败。
 */
export declare function indexGraph(includeDead: boolean): JsGraph
/** 链接解析结果：路径、锚点与歧义候选分开返回。 */
export interface JsLinkTarget {
  /** `resolved`、`ambiguous` 或 `dead`。 */
  status: string
  /** 唯一命中的库内路径；仅 `resolved` 提供。 */
  path?: string
  /** 歧义候选路径（升序）；仅 `ambiguous` 提供。 */
  candidates?: Array<string>
  /** 已解码的标题锚点；无锚点为缺失。 */
  anchor?: string
}
/**
 * 解析链接目标。
 *
 * `kind` 为 `wiki` 或 `md`。歧义时返回全部候选，由界面让用户选择。
 *
 * # Errors
 *
 * 未打开库或 kind 非法。
 */
export declare function linksResolve(from: string, raw: string, kind: string): JsLinkTarget
/** 一条索引中的链接。 */
export interface JsLinkRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 链接原文中的目标。 */
  toRaw: string
  /** 解析到的路径；死链、歧义和纯锚点为 `null`。 */
  toPath?: string
  /** `wiki` 或 `md`。 */
  kind: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
  /** `resolved`、`ambiguous`、`dead` 或 `self`。 */
  resolution: string
}
/** 一条已链接或未链接提及。 */
export interface JsMentionRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 源文件展示标题。 */
  fromTitle: string
  /** 源文件内容修改时间（自纪元起的纳秒）。 */
  mtime: number
  /** 命中区间起点（含）。 */
  startByte: number
  /** 命中区间终点（不含）。 */
  endByte: number
  /** 命中所在段落。 */
  snippet: string
  /** `linked` 或 `unlinked`。 */
  kind: string
  /** 已链接时为 `wiki`/`md`；未链接为 `null`。 */
  linkKind?: string
  /** 已链接为链接原文目标；未链接为命中文本。 */
  toRaw: string
}
/** 指向一篇笔记的已链接与未链接提及。 */
export interface JsMentions {
  /** 索引里的入链。 */
  linked: Array<JsMentionRecord>
  /** 正文里尚未做成链接的出现。 */
  unlinked: Array<JsMentionRecord>
}
/**
 * 指向 `path` 的入链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksTo(path: string): Array<JsLinkRecord>
/**
 * `path` 的出链。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexLinksFrom(path: string): Array<JsLinkRecord>
/**
 * 指向 `path` 的已链接提及与未链接提及。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexMentionsTo(path: string): JsMentions
/**
 * 把 `from` 文件里 `[start_byte, end_byte)` 的未链接提及就地转为指向
 * `target` 的 wiki 链接；`expected` 是查询时的提及文本，文件已变化时拒绝。
 *
 * # Errors
 *
 * 未打开库、目标不在库内、区间过期或写盘失败。
 */
export declare function mentionsLinkify(from: string, startByte: number, endByte: number, expected: string, target: string): JsRenameOutcome
/** 索引里的一条标题记录。 */
export interface JsHeadingRecord {
  /** 源文件相对路径。 */
  path: string
  /** 标题等级（1–6）。 */
  level: number
  /** 去除行内语法后的标题纯文本。 */
  text: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
}
/** 全库标签计数的一行。 */
export interface JsTagCount {
  /** 规范化标签（小写、无 `#`）。 */
  tag: string
  /** 携带该标签的文件数。 */
  count: number
}
/**
 * 全库标签及计数，标签升序；供标签浏览面板。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexTags(): Array<JsTagCount>
/** 一篇笔记可被点名的标题与别名。 */
export interface JsNoteKeys {
  /** 库内相对路径。 */
  path: string
  /** 展示标题：文首一级标题，缺失时为文件名词干。 */
  title: string
  /** frontmatter 别名，按书写顺序。 */
  aliases: Array<string>
}
/**
 * 全部 Markdown 笔记的标题与别名，路径升序；供快速切换器与别名补全。
 *
 * # Errors
 *
 * 未打开库或索引查询失败。
 */
export declare function indexNoteKeys(): Array<JsNoteKeys>
/**
 * `path` 的全部标题，按文档顺序；供锚点解析与标题补全。
 *
 * # Errors
 *
 * 未打开库。
 */
export declare function indexHeadings(path: string): Array<JsHeadingRecord>
/** 一页已验证命中；续页游标只能用于相同表达式、页长与库版本。 */
export interface JsSearchPage {
  /** 当前页文件。 */
  hits: Array<JsSearchHit>
  /** 没有更多命中时明确为 null。 */
  nextCursor: string | null
}
/** 同版本文件内的下一批具体命中，最多二十处。 */
export interface JsSearchMatchesPage {
  /** 本次新加载的位置与上下文。 */
  matches: Array<JsSearchMatch>
  /** 没有更多命中时明确为 null。 */
  nextCursor: string | null
}
/**
 * 提交异步搜索；新 ID 替代旧会话，同 ID 的文件和命中续页共享取消令牌。
 * 未打开库、参数、游标或索引错误会拒绝；取消不返回部分结果。
 */
export declare function searchQuery(query: JsSearchQuery, id: string, cursor?: string | undefined | null): Promise<JsSearchPage>
/** 加载当前搜索会话中的下一批命中；过期会话、游标或库版本会拒绝，不复活旧搜索。 */
export declare function searchMatches(query: JsSearchQuery, id: string, cursor: string): Promise<JsSearchMatchesPage>
/** 只取消匹配 ID 的任务；迟到的旧请求不能取消新查询，已完成或已关闭时可安全重试。 */
export declare function searchCancel(id: string): void
/**
 * 检索表达式节点；查询文本解析在渲染层完成。
 *
 * `kind` 为 `and`/`or`（`children` 为子条件）、`not`/`line`/`section`（恰好一个子条件）、
 * `term`/`regex`/`tag`/`path`/`file`（`value` 为文本）或 `attr`（`key` 必填，`value` 可缺）。
 */
export interface JsSearchExpr {
  /** 节点种类。 */
  kind: string
  /** 文本值；属性节点缺失表示只要求键存在。 */
  value?: string
  /** 属性名；只用于 `attr`。 */
  key?: string
  /** 子条件。 */
  children?: Array<JsSearchExpr>
}
/** 一次检索：表达式与每页文件数。 */
export interface JsSearchQuery {
  /** 检索表达式。 */
  expr: JsSearchExpr
  /** 每页文件数；非正数按内核默认值处理。 */
  limit: number
}
/** 一条搜索命中。 */
export interface JsSearchHit {
  /** 命中文件库内相对路径。 */
  path: string
  /** 展示标题。 */
  title: string
  /** 正文摘要；命中词以 U+0001/U+0002 控制字符包围，可能为空串。 */
  snippet: string
  /** 与命中范围同版本的文件 SHA-256。 */
  contentHash: string
  /** 首批最多五处具体命中，按正文顺序排列。 */
  matches: Array<JsSearchMatch>
  /** 去重后的精确正文命中总数。 */
  matchCount: number
  /** 单篇后续命中的游标，没有更多时明确为 null。 */
  matchesCursor: string | null
}
/** 一处命中的源码位置与上下文。 */
export interface JsSearchMatch {
  /** 无法证明源码映射时不返回位置，禁止用同名词猜测。 */
  location: JsSearchLocation | null
  /** 本处命中的高亮上下文。 */
  snippet: string
}
/** UTF-8 源码区间；范围仅对结果携带的内容版本有效。 */
export interface JsSearchLocation {
  /** 起点（含）。 */
  startByte: number
  /** 终点（不含）。 */
  endByte: number
  /** 一基行号。 */
  line: number
}
/** 开库阶段计数；准备期间可取消，提交会话后的状态替换不可中断。 */
export interface JsOpenProgress {
  /** recovering、scanning、checking、reading、indexing、ranking 或 verifying。 */
  phase: string
  /** 当前阶段已完成条目数。 */
  completed: number
  /** 未知总量时缺省，不生成虚构的总体百分比。 */
  total?: number
}
/** 监视通知携带受影响路径及健康状态；失败不能伪装成一次成功刷新。 */
export interface JsVaultEvent {
  /** changed、watch-error 或 index-error。 */
  status: string
  /** 已约束到当前库的相对路径，空列表表示需要完整刷新。 */
  paths: Array<string>
  /** 本次确实完成了监视后的索引校验。 */
  healthy: boolean
  /** 异常原因；成功事件不提供。 */
  message?: string
}
/**
 * 打开库并开始监视。
 *
 * `root` 是库目录，`index_dir` 是库外的派生索引与恢复目录。
 * 监视线程在防抖与索引刷新后，将 `on_changed` 投递给持有内核的 JS 线程。
 * 成功后替换当前库及其监视器；失败时保留原库。
 * `progress` 返回 false 时取消准备；`before_commit` 接收已准备目录并提交外部会话，
 * 返回 false 同样取消。两个回调都不可重入内核。返回 true 表示已切库，false 表示取消。
 *
 * # Errors
 *
 * 打不开目录、索引或监视器时失败。
 */
export declare function vaultOpen(root: string, indexDir: string, onChanged: (...args: any[]) => any, progress?: ((progress: JsOpenProgress) => boolean) | undefined | null, beforeCommit?: ((entries: JsVaultEntry[]) => boolean) | undefined | null): boolean
/**
 * 关闭当前库并停止监视。
 *
 * # Errors
 *
 * 锁毒化时失败。
 */
export declare function vaultClose(): void
