/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 独占导入的附件位置和提交后警告。 */
export interface JsImportedAttachment {
  /** 实际库内路径，同名避让后可能与原文件名不同。 */
  path: string
  /** 文件已落盘后发生的索引或同步错误。 */
  warning?: string
}
/** 一条书签；`kind` 为 `file`/`folder`（`path`）、`heading`（`path` 与 `heading`）或 `search`（`query`）。 */
export interface JsBookmark {
  /** 书签种类。 */
  kind: string
  /** 库内相对路径；文件、文件夹与标题书签必填。 */
  path?: string
  /** 标题原文；只用于标题书签。 */
  heading?: string
  /** 查询文本；只用于搜索书签。 */
  query?: string
  /** 自定义显示名。 */
  title?: string
}
/** 文件树条目，包含空文件夹。 */
export interface JsVaultEntry {
  /** 库内相对路径。 */
  path: string
  /** file 或 directory。 */
  kind: string
  /** 仅在草稿无法对应真实文件条目时设置。 */
  recoveryOnly?: boolean
}
/** 文件已经完成改名，索引或日志清理可能仍需重试。 */
export interface JsRenameOutcome {
  /** 提交后的警告；无警告时缺失。 */
  warning?: string
}
/** 已持久化的恢复草稿。 */
export interface JsDraft {
  /** 普通草稿为最新内容；存在 editor 时为重建源码映射的原始字节。 */
  bytes: Buffer
  /** 原编辑基准；缺失表示新文件。 */
  base?: Buffer
  /** 版本化的编辑器恢复内容；没有时按普通 Markdown 字节恢复。 */
  editor?: string
}
/** 编辑器加载快照，文件删除时仍可恢复草稿。 */
export interface JsFileSnapshot {
  /** 磁盘内容；缺失时通过 disk_error 区分删除与读取失败。 */
  disk?: Buffer
  /** 原路径不可读时保留草稿，并携带原因。 */
  diskError?: string
  /** 尚未提交的编辑。 */
  draft?: JsDraft
}
/** 文件提交结果，冲突时附带磁盘版本。 */
export interface JsWriteResult {
  /** `saved` 或 `conflict`。 */
  status: string
  /** 冲突的磁盘字节；缺失也可能表示文件被删除。 */
  disk?: Buffer
  /** 已提交后的同步、索引或清理警告。 */
  warning?: string
}
/** 新副本的路径与提交后警告。 */
export interface JsSavedCopy {
  /** 实际创建的相对路径。 */
  path: string
  /** 内容已保存后的警告。 */
  warning?: string
}
/** 链接解析结果：路径、锚点与歧义候选分开返回。 */
export interface JsLinkTarget {
  /** `resolved`、`ambiguous` 或 `dead`。 */
  status: string
  /** 唯一命中的库内路径；仅 `resolved` 提供。 */
  path?: string
  /** 歧义候选路径（升序）；仅 `ambiguous` 提供。 */
  candidates?: Array<string>
  /** 已解码的标题锚点；无锚点为缺失。 */
  anchor?: string
}
/** 一条索引中的链接。 */
export interface JsLinkRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 链接原文中的目标。 */
  toRaw: string
  /** 解析到的路径；死链、歧义和纯锚点为 `null`。 */
  toPath?: string
  /** `wiki` 或 `md`。 */
  kind: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
  /** `resolved`、`ambiguous`、`dead` 或 `self`。 */
  resolution: string
}
/** 一条已链接或未链接提及。 */
export interface JsMentionRecord {
  /** 源文件相对路径。 */
  fromPath: string
  /** 源文件展示标题。 */
  fromTitle: string
  /** 源文件内容修改时间（自纪元起的纳秒）。 */
  mtime: number
  /** 命中区间起点（含）。 */
  startByte: number
  /** 命中区间终点（不含）。 */
  endByte: number
  /** 命中所在段落。 */
  snippet: string
  /** `linked` 或 `unlinked`。 */
  kind: string
  /** 已链接时为 `wiki`/`md`；未链接为 `null`。 */
  linkKind?: string
  /** 已链接为链接原文目标；未链接为命中文本。 */
  toRaw: string
}
/** 指向一篇笔记的已链接与未链接提及。 */
export interface JsMentions {
  /** 索引里的入链。 */
  linked: Array<JsMentionRecord>
  /** 正文里尚未做成链接的出现。 */
  unlinked: Array<JsMentionRecord>
}
/** 索引里的一条标题记录。 */
export interface JsHeadingRecord {
  /** 源文件相对路径。 */
  path: string
  /** 标题等级（1–6）。 */
  level: number
  /** 去除行内语法后的标题纯文本。 */
  text: string
  /** 字节区间起点（含）。 */
  startByte: number
  /** 字节区间终点（不含）。 */
  endByte: number
}
/** 全库标签计数的一行。 */
export interface JsTagCount {
  /** 规范化标签（小写、无 `#`）。 */
  tag: string
  /** 携带该标签的文件数。 */
  count: number
}
/** 一篇笔记可被点名的标题与别名。 */
export interface JsNoteKeys {
  /** 库内相对路径。 */
  path: string
  /** 展示标题：文首一级标题，缺失时为文件名词干。 */
  title: string
  /** frontmatter 别名，按书写顺序。 */
  aliases: Array<string>
}
/** 一页已验证命中；续页游标只能用于相同表达式、页长与库版本。 */
export interface JsSearchPage {
  /** 当前页文件。 */
  hits: Array<JsSearchHit>
  /** 没有更多命中时明确为 null。 */
  nextCursor: string | null
  /** 融合结果的语义覆盖；严格查询省略。 */
  semantic?: JsSemanticStatus
  /** 融合召回是否达到候选预算。 */
  limited?: boolean
}
/** 同版本文件内的下一批具体命中，最多二十处。 */
export interface JsSearchMatchesPage {
  /** 本次新加载的位置与上下文。 */
  matches: Array<JsSearchMatch>
  /** 没有更多命中时明确为 null。 */
  nextCursor: string | null
}
/**
 * 检索表达式节点；查询文本解析在渲染层完成。
 *
 * `kind` 为 `and`/`or`（`children` 为子条件）、`not`/`line`/`section`（恰好一个子条件）、
 * `term`/`regex`/`tag`/`path`/`file`（`value` 为文本）或 `attr`（`key` 必填，`value` 可缺）。
 */
export interface JsSearchExpr {
  /** 节点种类。 */
  kind: string
  /** 文本值；属性节点缺失表示只要求键存在。 */
  value?: string
  /** 属性名；只用于 `attr`。 */
  key?: string
  /** 子条件。 */
  children?: Array<JsSearchExpr>
}
/** 一次检索：表达式与每页文件数。 */
export interface JsSearchQuery {
  /** 检索表达式。 */
  expr?: JsSearchExpr
  /** hybrid 表示融合查询；省略表示既有严格查询。 */
  kind?: string
  /** 融合文本。 */
  text?: string
  /** 融合硬筛选。 */
  filter?: JsSearchExpr
  /** 每页文件数；非正数按内核默认值处理。 */
  limit: number
}
/** 一条搜索命中。 */
export interface JsSearchHit {
  /** 命中文件库内相对路径。 */
  path: string
  /** 展示标题。 */
  title: string
  /** 正文摘要；命中词以 U+0001/U+0002 控制字符包围，可能为空串。 */
  snippet: string
  /** 与命中范围同版本的文件 SHA-256。 */
  contentHash: string
  /** 首批最多五处具体命中，按正文顺序排列。 */
  matches: Array<JsSearchMatch>
  /** 去重后的精确正文命中总数。 */
  matchCount: number
  /** 单篇后续命中的游标，没有更多时明确为 null。 */
  matchesCursor: string | null
  /** 融合来源证据，不能计入精确正文命中数。 */
  evidence?: Array<JsHybridEvidence>
}
/** 一处命中的源码位置与上下文。 */
export interface JsSearchMatch {
  /** 无法证明源码映射时不返回位置，禁止用同名词猜测。 */
  location: JsSearchLocation | null
  /** 本处命中的高亮上下文。 */
  snippet: string
}
/** UTF-8 源码区间；范围仅对结果携带的内容版本有效。 */
export interface JsSearchLocation {
  /** 起点（含）。 */
  startByte: number
  /** 终点（不含）。 */
  endByte: number
  /** 一基行号。 */
  line: number
}
/** 语义模型和索引覆盖状态。 */
export interface JsSemanticStatus {
  /** missing、indexing、ready 或 error。 */
  state: string
  /** 已完成的有效笔记数。 */
  indexed: number
  /** Markdown 笔记总数。 */
  total: number
  /** 具体故障原因。 */
  message: string | null
}
/** 一条相关段落或纠错证据；位置属于结果携带的内容版本。 */
export interface JsHybridEvidence {
  /** lexical、fuzzy 或 semantic。 */
  kind: string
  /** 原文摘要。 */
  snippet: string
  /** 可证明的源码范围。 */
  location: JsSearchLocation | null
}
/** 监视事件携带代次，主线程交付时过滤已关闭的库。 */
export interface JsVaultEvent {
  /** 原生运行时代次；不暴露给渲染进程。 */
  generation: string
  /** changed、watch-error 或 index-error。 */
  status: string
  /** 受影响的库内路径；空表示完整刷新。 */
  paths: Array<string>
  /** 是否完成索引复核。 */
  healthy: boolean
  /** 失败时保留原因。 */
  message?: string
}
/** 一个宿主的 Rust 运行时；显式 shutdown 负责等待磁盘任务与监听退出。 */
export declare class NativeRuntime {
  /** 导入用户选择的附件字节，返回实际位置；路径、大小与写盘错误由内核传播。 */
  attachmentImport(root: string, from: string, name: string, bytes: Buffer): Promise<JsImportedAttachment>
  /**
   * 读出库内书签；文件不存在时为空。
   *
   * # Errors
   *
   * 未打开库、读盘失败或书签文件损坏。
   */
  bookmarksList(): Promise<Array<JsBookmark>>
  /**
   * 整体替换书签清单；损坏的旧文件先备份再覆盖。
   *
   * # Errors
   *
   * 未打开库、书签字段无效或写盘失败。
   */
  bookmarksSet(items: Array<JsBookmark>): Promise<void>
  /**
   * 列出库内相对路径。
   *
   * # Errors
   *
   * 未打开库或读目录失败。
   */
  vaultList(): Promise<Array<string>>
  /** 列出完整目录；未打开库或目录读取失败时返回错误。 */
  vaultEntries(): Promise<Array<JsVaultEntry>>
  /**
   * 创建笔记或文件夹；`content` 是文件初始字节（缺省为空），创建与写入
   * 是同一次独占提交。非法类型、同名目标、目录携带内容或磁盘失败时拒绝。
   */
  entryCreate(path: string, kind: string, content?: Buffer | undefined | null): Promise<JsRenameOutcome>
  /** 移入系统废纸篓；失败不退化为永久删除，未保存草稿阻止操作。 */
  entryTrash(path: string): Promise<JsRenameOutcome>
  /** 获取经过库根校验的现有路径，只供主进程调用系统文件管理器。 */
  entryPath(path: string): Promise<string>
  /**
   * 将 `from` 改名为 `to` 并更新全库链接，返回提交后的警告。
   *
   * # Errors
   *
   * 未打开库、目标已存在或写盘失败。
   */
  entryRename(from: string, to: string): Promise<JsRenameOutcome>
  /** 执行整批请求；返回真实完成前缀，取消只能发生在事务边界。 */
  entryBatch(request: unknown, control: NativeControl): Promise<unknown>
  /** 启动时核实未确认的导出结果，不自动重放原来的生成或覆盖操作。 */
  exportRecover(): Promise<unknown>
  /** 保存门禁后准备导出；控制句柄不经过磁盘任务队列。 */
  exportPrepare(root: string, id: string, paths: Array<string> | undefined | null, hidden: boolean, control: NativeControl): Promise<unknown>
  /** 原生校验动作和路径；动作不会作为通用文件系统能力暴露给页面。 */
  exportAction(id: string, action: any, bytes?: Buffer | undefined | null): Promise<unknown>
  /**
   * 读取文件原始字节。
   *
   * # Errors
   *
   * 未打开库、越界或不存在。
   */
  fileRead(rel: string): Promise<Buffer>
  /**
   * 获取 `rel` 的磁盘内容与恢复草稿。
   *
   * # Errors
   *
   * 未打开库、越界或读取失败。
   */
  fileSnapshot(rel: string): Promise<JsFileSnapshot>
  /**
   * 持久化带版本的编辑恢复数据，保持原笔记字节不变。
   *
   * # Errors
   * 未打开库、路径或数据非法、恢复记录冲突或数据库不可写。
   */
  filePreserveDraft(rel: string, source: Buffer, expected: Buffer | undefined | null, editor: string): Promise<void>
  /**
   * 按 `expected` 基准保存 `bytes`，返回提交状态或冲突。
   *
   * # Errors
   *
   * 未打开库、越界、草稿持久化或内容提交失败。
   */
  fileWrite(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): Promise<JsWriteResult>
  /**
   * 将当前 `bytes` 写入唯一命名的新副本，`expected` 用于恢复基准。
   *
   * # Errors
   *
   * 未打开库、路径非法或副本提交失败。
   */
  fileWriteCopy(rel: string, bytes: Buffer, expected?: Buffer | undefined | null): Promise<JsSavedCopy>
  /**
   * 解析链接目标。
   *
   * `kind` 为 `wiki` 或 `md`。歧义时返回全部候选，由界面让用户选择。
   *
   * # Errors
   *
   * 未打开库或 kind 非法。
   */
  linksResolve(from: string, raw: string, kind: string): Promise<JsLinkTarget>
  /**
   * 指向 `path` 的入链。
   *
   * # Errors
   *
   * 未打开库。
   */
  indexLinksTo(path: string): Promise<Array<JsLinkRecord>>
  /**
   * `path` 的出链。
   *
   * # Errors
   *
   * 未打开库。
   */
  indexLinksFrom(path: string): Promise<Array<JsLinkRecord>>
  /**
   * 指向 `path` 的已链接提及与未链接提及。
   *
   * # Errors
   *
   * 未打开库。
   */
  indexMentionsTo(path: string): Promise<JsMentions>
  /**
   * 把 `from` 文件里 `[start_byte, end_byte)` 的未链接提及就地转为指向
   * `target` 的 wiki 链接；`expected` 是查询时的提及文本，文件已变化时拒绝。
   *
   * # Errors
   *
   * 未打开库、目标不在库内、区间过期或写盘失败。
   */
  mentionsLinkify(from: string, startByte: number, endByte: number, expected: string, target: string): Promise<JsRenameOutcome>
  /**
   * 全库标签及计数，标签升序；供标签浏览面板。
   *
   * # Errors
   *
   * 未打开库。
   */
  indexTags(): Promise<Array<JsTagCount>>
  /**
   * 全部 Markdown 笔记的标题与别名，路径升序；供快速切换器与别名补全。
   *
   * # Errors
   *
   * 未打开库或索引查询失败。
   */
  indexNoteKeys(): Promise<Array<JsNoteKeys>>
  /**
   * `path` 的全部标题，按文档顺序；供锚点解析与标题补全。
   *
   * # Errors
   *
   * 未打开库。
   */
  indexHeadings(path: string): Promise<Array<JsHeadingRecord>>
  /** 创建轻量句柄；初始化不读取磁盘，首个应用命令在后台执行。 */
  constructor(userData: string, onChanged: (event: JsVaultEvent) => void)
  /** 当前代次只访问原子内存，供宿主丢弃迟到事件。 */
  get generation(): string
  /** 关闭入口并排空所有已接受任务；Promise 完成才表示监听已停止。 */
  shutdown(): Promise<void>
  /** 提交搜索；在调用线程登记会话，旧续页不能替换新搜索。 */
  searchQuery(query: JsSearchQuery, id: string, cursor?: string | undefined | null): Promise<JsSearchPage>
  /** 同会话的命中续页共享取消令牌，交付前再次验证归属。 */
  searchMatches(query: JsSearchQuery, id: string, cursor: string): Promise<JsSearchMatchesPage>
  /** 取消仅匹配 ID 的会话，不经过磁盘队列。 */
  searchCancel(id: string): void
  /** 在选择本地目录前登记安装会话；明确取消或切库后不能重新启动旧安装。 */
  searchModelBegin(id: string): void
  /** 取消指定模型安装；普通搜索会话保持有效。 */
  searchModelCancel(id: string): void
  /** 下载或导入固定 Harrier 模型并调度当前库索引；只等待模型安装，不阻塞保存。 */
  searchModelInstall(source: string | undefined | null, id: string): Promise<JsSemanticStatus>
  /** 准备候选库并原子切换；取消返回 null，失败保留旧库。 */
  vaultOpen(root: string, control: NativeControl): Promise<unknown>
  /** 在后台创建默认目录并打开，主线程只负责提供系统路径。 */
  vaultCreate(root: string, control: NativeControl): Promise<unknown>
  /** 从磁盘会话恢复原库与阅读现场；失败不覆盖原会话。 */
  vaultRestore(control: NativeControl): Promise<unknown>
  /** 顺序关闭当前库，等待监视线程退出。 */
  vaultClose(): Promise<void>
  /** 读取兼容旧格式的应用会话；磁盘错误按现有恢复规则回退。 */
  sessionLoad(): Promise<unknown>
  /** 仅替换应用字段；输入由主进程校验，Rust 仍归一化磁盘格式。 */
  sessionPatch(patch: unknown): Promise<void>
  /** 合并阅读器会话，不允许覆盖窗口和外观字段。 */
  readerSessionPatch(patch: unknown): Promise<void>
  /** 目录状态绑定库根，迟到的旧状态不能覆盖新库。 */
  readerFileTreeSave(root: string, tree: unknown): Promise<void>
}
/** 内存控制句柄，取消和进度不排在正在执行的操作之后。 */
export declare class NativeControl {
  /** 创建可取消操作；磁盘工作由持有句柄的命令负责。 */
  constructor()
  /** 原子请求取消；已经提交的操作返回 false。 */
  cancel(): boolean
  /** 读取取消标记，目录对话框结束后仍能识别此前的取消。 */
  get cancelled(): boolean
  /** 当前阶段完整快照，不等待任何磁盘任务。 */
  get progress(): unknown
}
