packages:
  - modules/notes/packages/desktop
  - modules/notes/packages/vault-node

allowBuilds:
  electron: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@mermaid-js/parser@2.0.1'
  - '@zip.js/zip.js@2.23.0'
  - mermaid@12.1.0
