/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 在闭合轮次之后派生历史并交付安全投影；不启动资源，原检查点保持不变。
 * checkpoint 为宿主私有 JSON，turn_id 省略时复制当前完整检查点；校验失败拒绝 Promise。
 */
export declare function branchCheckpoint(checkpoint: string, turnId?: string | undefined | null): Promise<string>
/** 用户重新打开迁移后的笔记库时重绑静态历史；失败拒绝，不启动模型或工具。 */
export declare function relocateCheckpoint(checkpoint: string, workspace: string): Promise<string>
/** 一条桌面对话的原生资源句柄；关闭 Promise 完成才表示运行和终端已回收。 */
export declare class NativeAgentSession {
  /** 解析宿主目录、权限与初始模型；不运行模型或 shell，通知合并为一个待交付事件。 */
  constructor(configuration: string, changed: () => void)
  /** 快照不消费输出；供应商原生签名和认证配置不包含在结果中。 */
  snapshot(): string
  /** 中断明确的运行并等待终态；旧运行标识、超时或关闭错误会拒绝 Promise。 */
  interrupt(runId: string): Promise<void>
  /** 返回仅可信主进程可持久化的闭合历史，不包含认证或可复用的进程句柄。 */
  checkpoint(): string
  /** 仅向新会话恢复相同工作区的记录；非法历史、版本不符或已使用的会话均拒绝。 */
  restore(checkpoint: string): void
  /** 启动一轮任务，返回宿主运行标识；实际进度通过快照读取。 */
  start(text: string, context?: string | undefined | null): string
  /**
   * 每轮使用主进程最新模型配置，后台资源保持会话归属。
   * configuration 为不超过 1 MiB 的模型 JSON，binding 为可信主进程计算的连接指纹。
   * text 为本轮任务，context 为可选文章事实；返回运行标识，不自动重放旧任务。
   * 配置、历史或上下文无效，或会话关闭、正在运行时返回错误，不修改已有运行。
   */
  startConfigured(configuration: string, binding: string, text: string, context?: string | undefined | null): string
  /** 取消当前运行和审批，不自动重放命令。 */
  cancel(): void
  /**
   * 只有可信宿主可以交还人工持有的浏览器，模型工具不暴露恢复控制动作。
   * resume 为 true 表示交还，为 false 表示接管；env 将异步回执适配为 Promise<string>。
   * 会话关闭、运行占用、浏览器不可用或 Node-API 适配失败时拒绝 Promise 或返回错误。
   */
  browserControl(resume: boolean): Promise<string>
  /** 只回复当前有效且类型匹配的申请，迟到批准被拒绝。 */
  approve(id: string, decision: string): void
  /** 独立读取原始终端页，偏移为整数十进制字符串，避免 JS 数字精度损失。 */
  readTerminal(id: string, offset: string, limit: number): Promise<string>
  /** 将键盘或粘贴字节送入终端，不消费模型增量结果。 */
  sendInput(id: string, input: Buffer, closeStdin: boolean): Promise<void>
  /** 排队停止终端，退出确认通过后续快照交付。 */
  stopTerminal(id: string): void
  /** 宿主终端动作与模型调用经过同一参数和归属检查。 */
  terminalAction(arguments: string): Promise<string>
  /** 永久关闭会话并等待真实停机，窗口关闭与应用退出均使用此入口。 */
  close(): Promise<void>
}
