/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 一条桌面对话的原生资源句柄；关闭 Promise 完成才表示运行和终端已回收。 */
export declare class NativeAgentSession {
  /** 解析宿主提供的冻结配置；不运行模型或 shell，通知合并为一个待交付状态变化。 */
  constructor(configuration: string, changed: () => void)
  /** 快照不消费输出；供应商原生签名和认证配置不包含在结果中。 */
  snapshot(): string
  /** 启动一轮任务，返回宿主运行标识；实际进度通过快照读取。 */
  start(text: string): string
  /** 取消当前运行和审批，不自动重放命令。 */
  cancel(): void
  /**
   * 只有可信宿主可以交还人工持有的浏览器，模型工具不暴露恢复控制动作。
   * resume 为 true 表示交还，为 false 表示接管；env 将异步回执适配为 Promise<string>。
   * 会话关闭、运行占用、浏览器不可用或 Node-API 适配失败时拒绝 Promise 或返回错误。
   */
  browserControl(resume: boolean): Promise<string>
  /** 只回复当前有效且类型匹配的申请，迟到批准被拒绝。 */
  approve(id: string, decision: string): void
  /** 独立读取原始终端页，偏移为整数十进制字符串，避免 JS 数字精度损失。 */
  readTerminal(id: string, offset: string, limit: number): Promise<string>
  /** 将键盘或粘贴字节送入终端，不消费模型增量结果。 */
  sendInput(id: string, input: Buffer, closeStdin: boolean): Promise<void>
  /** 排队停止终端，退出确认通过后续快照交付。 */
  stopTerminal(id: string): void
  /** 宿主终端动作与模型调用经过同一参数和归属检查。 */
  terminalAction(arguments: string): Promise<string>
  /** 永久关闭会话并等待真实停机，窗口关闭与应用退出均使用此入口。 */
  close(): Promise<void>
}
